### ISSUE TITLE
Rungsiman

### ISSUE THREAD

**Issue by Ratchaphoom** [HitomiFRIEND/FoolTeam#1]
@HitomiFRIEND  

ldjlflksjlfjslkdflkslflkslkjdlkfjksljdflkslkjdkflsdf

**Comment by Ratchaphoom** [comment]
@sapolayot 
ksdjfjskdjflsjfdjlsjldjflsjdfljsdlkfjlsdjlkfsldjfljlksjdlfj

**Comment by sapolayot** [comment]
fuckkkkkkk

**Comment by HitomiFRIEND** [comment]
kuoyyyyyyyyyyyyyyyy
